### ISSUE TITLE
Call to undefined method getResourceOwner()

### ISSUE THREAD

**Issue by sidati** [thephpleague/oauth2-google#10]
Hello,
First of all thank you for your contribution, secondly i'm using your example in readme file, but its seems that the function which fetch the user details doesn't exists :

<code>Fatal error:  Call to undefined method League\OAuth2\Client\Provider\Google::getResourceOwner() in /var/www/api/index.php on line 268
</code>

Not sure if this because i'm using an old version or what ?? ive also used "getUserDetails" method but an unknown error message pear, can you please give me some help,

Sidati,
Best

**Comment by shadowhand** [comment]
You are using a pre-1.0 (beta) version. Refer to [v0.2 docs](https://github.com/thephpleague/oauth2-google/tree/v0.2.0).

**Comment by shadowhand** [comment]
But really, you don't need the oauth2-google package if you are using a pre-1.0 version, because all the providers are included in the main [oauth2-client package, version 0.12 or less](https://github.com/thephpleague/oauth2-client/tree/0.12.x).
