### ISSUE TITLE
Legacy People API?

### ISSUE THREAD

**Issue by Razviar** [thephpleague/oauth2-google#113]
Hello! When I'm trying to get user data like this:

$token = $google_client->getAccessToken('authorization_code', [
        'code' => $_GET['code']
    ]);
$data = $google_client->getResourceOwner($token);
$email = $data->getEmail();

I'm getting following error:
PHP Fatal error:  Uncaught League\OAuth2\Client\Provider\Exception\IdentityProviderException: Legacy People API has not been used in project 324673849993 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/legacypeople.googleapis.com/overview?project=324673849993 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.

Google doesn't let me to enable this API (just returns error when I open the URL). Is there any option to use not legacy people API?

**Comment by Razviar** [comment]
Fixed myself, making a commit

**Comment by shadowhand** [comment]
@Razviar you probably have a different version locked in composer.json, or you are using an older version of PHP that is preventing updates.
