### ISSUE TITLE
implement scopes setting

### ISSUE THREAD

**Issue by vipconsult** [thephpleague/oauth2-google#12]
Is there any reasons why scopes have been removed ?

and if this is by design why do we need the scope openid ? isn't email and profile info enough ?

**Comment by shadowhand** [comment]
You can extend the Google provider and change `getDefaultScopes` to whatever you want.

The scope `openid` ensures that the response includes the Google user id, which is the unique identifier for the user without having to fetch the user details. This helps for identifying users, especially when migrating from other implementations.

**Comment by shadowhand** [comment]
Or you can use `getAuthorizationUrl` to pass your preferred scopes:

```php
$url = $provider->getAuthorizationUrl([
    'scopes' => [ ... ],
]);
```
