### ISSUE TITLE
Future Support for PHP 8.2 and 8.3

### ISSUE THREAD

**Issue by ZXRoxas** [thephpleague/oauth2-google#122]
To Whom This May Concern,

I was curious to know if PHP 8.2 and 8.3 were going to be added as supported versions in the near future?

Thanks!

**Comment by shadowhand** [comment]
@ZXRoxas PHP 8.2 and 8.3 are already supported, per the composer.json requirements. But as you noted, they were not included in the README list, which I have just updated.
