### ISSUE TITLE
Add ability to authenticate using id_token 

### ISSUE THREAD

**Issue by bePolite** [thephpleague/oauth2-google#14]
https://developers.google.com/api-client-library/php/guide/aaa_idtoken

**Comment by joariasl** [comment]
I am searching the same!

**Comment by shadowhand** [comment]
`AccessToken::getValues()` was introduced in oauth2-client v1.4.0 to resolve this issue.

**Comment by DonPrus** [comment]
I update information in https://github.com/thephpleague/oauth2-google/issues/35.
May be it helps somebody.
