### ISSUE TITLE
Can't see a way to set `accessType`

### ISSUE THREAD

**Issue by Synchro** [thephpleague/oauth2-google#18]
The `accessType` property has been changed to protected, but now I can't see any way of setting it, and it's broken the PHPMailer google oauth setup script. The google API has a ['setAccessType` method](https://developers.google.com/identity/protocols/OAuth2WebServer#offline), so I assume an equivalent is missing from this Provider lib?

I found access was provided in [this commit](https://github.com/thephpleague/oauth2-google/commit/c7334f8f544fa8148e6648298baf0a1500aca980), but that seems to have disappeared in later versions.

**Comment by Synchro** [comment]
I see access was removed in [this commit](https://github.com/thephpleague/oauth2-google/commit/e190d0b3c1a3c24e43e05ce40ab20b4420cf706e#diff-44f351f030488e63152615e12d7ac64cL41). I now see that it can be set via the constructor, but why remove read access when the property remains?

**Comment by shadowhand** [comment]
You can set it via the constructor, like every other property in the class. It is [documented in the README](https://github.com/thephpleague/oauth2-google/blob/cf02438bee65426913f79027ce920eef84ea6ce9/README.md#refreshing-a-token).

**Comment by Synchro** [comment]
I know - I mentioned that above, but you can't read its value because `getAccessType()` was removed. Similarly, the README says you can access `$provider->state;`, but you can't do that either - you must use `getState()`.

**Comment by shadowhand** [comment]
Why would you need to read the access type? Especially since you are passing the value in, you already know it.

**Comment by shadowhand** [comment]
@Synchro thanks for pointing out the issue with `getState` in the README, I fixed it.
