### ISSUE TITLE
Google id_token

### ISSUE THREAD

**Issue by koxon** [thephpleague/oauth2-google#19]
Hello,

I am still using the oauth2 0.12 version due to Guzzle version conflicts in my project.

As per Google specs, it is returning an id_token along with the access_token and refresh_token.
See: https://developers.google.com/identity/protocols/OpenIDConnect?hl=en#exchangecode

I don't see this token as part of the returned value from the library.

Am I missing something? How can I get this id_token?

Thanks guys
nicolas

**Comment by shadowhand** [comment]
Neither v0.x or v1.x of the GoogleProvider capture that value, since it is not included in the spec. However, you don't need this value, since the user details will provide the same information. If you really did want to capture it, you could use the [GrantFactory in v1.x](https://github.com/thephpleague/oauth2-client/blob/master/src/Grant/GrantFactory.php) to write an extension of the grant to capture it.

**Comment by koxon** [comment]
Hi,

Thank you i Will take a look
Nico

**Comment by koxon** [comment]
Hey Woody.

Which specs are you referring to?
The google specs are mentioning it :
https://developers.google.com/identity/protocols/OpenIDConnect?hl=en#exchangecode

ᐧ

On Fri, Nov 6, 2015 at 9:12 AM, Nicolas Menciere <nmenciere@sportarchive.tv>
wrote:

> Hi,
>
> Thank you i Will take a look
> Nico
> On Nov 6, 2015 9:10 AM, "Woody Gilk" <notifications@github.com> wrote:
>
>> Neither v0.x or v1.x of the GoogleProvider capture that value, since it
>> is not included in the spec. However, you don't need this value, since the
>> user details will provide the same information. If you really did want to
>> capture it, you could use the GrantFactory in v1.x
>> <https://github.com/thephpleague/oauth2-client/blob/master/src/Grant/GrantFactory.php>
>> to write an extension of the grant to capture it.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/thephpleague/oauth2-google/issues/19#issuecomment-154418116>
>> .
>>
>


-- 
Nicolas Menciere
Co-Founder and CTO
Sport Archive Inc.

**Comment by shadowhand** [comment]
@koxon http://tools.ietf.org/html/rfc6750#section-4
