### ISSUE TITLE
no ACCESS_TOKEN_UID in response

### ISSUE THREAD

**Issue by basz** [thephpleague/oauth2-google#2]
When I do the following

```
$token = $provider->getAccessToken('authorization_code', ['code' => $data->authorization_code]);
```
I get the following error
```
Undefined index: id in ./vendor/league/oauth2-client/src/Provider/AbstractProvider.php on line 444
```
The static::ACCESS_TOKEN_UID == 'id' and is not available in the response
```
    protected function prepareAccessTokenResult(array $result)
    {
        trigger_error(json_encode($result));
        if (static::ACCESS_TOKEN_UID) {
            $result['uid'] = $result[static::ACCESS_TOKEN_UID];
        }
        return $result;
    }
```
```
{"access_token":"xxx....xxx","token_type":"Bearer","expires_in":3600,"id_token":"xxx....xxx"
```

**Comment by basz** [comment]
@shadowhand is the id_token the intended ACCESS_TOKEN_UID instead of 'id'?

ACCESS_TOKEN_UID should be deleted or changed...
or the client package should use an `$result[static::ACCESS_TOKEN_UID]` in the if statement

please advise and I'll PR

**Comment by shadowhand** [comment]
@basz could you try the newest version and see if this is still an issue?

**Comment by onema** [comment]
I can confirm that this is still an issue as 

```
Notice: Undefined index: id .../vendor/league/oauth2-client/src/Provider/AbstractProvider.php on line 660
```
The call to this method is done form: `.../AbstractProvider.php:491`. The response array does not contain an `id` key, nor it has the `client_id` value (which I believe should map to the resource owner id?)

**Comment by shadowhand** [comment]
Alright I'll get my examples updated and figure out what is going wrong. Thanks for the feedback!

**Comment by onema** [comment]
After an update, I still get the same error. I use my own custom scopes. The `ACCESS_TOKEN_RESOURCE_OWNER_ID` is still not available in the final set of tokens.

**Comment by shadowhand** [comment]
You need to include `openid` in your scopes or the `id` won't come back.

**Comment by onema** [comment]
Okay, I have added the `openid` scope, and used the default scopes, but I still get the same error and the `getResourceOwnerId` returns null. 

Is `ACCESS_TOKEN_RESOURCE_OWNER_ID` supposed to be the same as the `client_id`? 

If this is the case, the `client_id` is returned on every successful code grant regardless of the scope (before [requesting the access token](https://github.com/thephpleague/oauth2-client/blob/1.0.0-beta1/src/Provider/AbstractProvider.php#L482)).

**Comment by onema** [comment]
Actually the `@dev` version of the `oauth2-client` addresses the warning, but unfortunately I'm still not able to get the resource owner id :(

**Comment by shadowhand** [comment]
Are you revoking the token before attempting to login again?

And no, `client_id` is not the same as `id`.

**Comment by shadowhand** [comment]
I can't reproduce this. So long as you haven't modified the `fields` that are requested, you should always get a `id` back with the `profile` scope.

You can try the [api explorer](https://developers.google.com/apis-explorer/?hl=en_US#p/plus/v1/plus.people.get?userId=me&fields=name%252Fformatted%252Cemails%252Fvalue%252Cimage%252Furl%252Cid&_h=1&) to verify.
