### ISSUE TITLE
Example setup the GoogleConsole

### ISSUE THREAD

**Issue by huglester** [thephpleague/oauth2-google#21]
Hello,

I did set up FB with thephpleague without any troubles.

But is there any example on setting up the google console? 
I was following this one: https://developers.google.com/identity/protocols/OAuth2WebServer
but did not go far. On the redirect I get:

```
Google Apps Error:
Server error
Sorry, you've reached a login page for a domain that isn't using Google Apps. Please check the web address and try again.
```

Btw you can test google login local domains like: http://site1.app, right?

**Comment by huglester** [comment]
Ok, I figured out.
Needed to set 'hostedDomain' to null
Also needed to enable 'Google+ API' in the console.

Example did help! https://github.com/thephpleague/oauth2-google/tree/master/examples

**Comment by shadowhand** [comment]
Glad you were able to figure it out!
