### ISSUE TITLE
google code return "#"

### ISSUE THREAD

**Issue by iFunbox** [thephpleague/oauth2-google#24]
?code=4/vAiLWXkmXj1nyNF3hIxz4R6TI2hoGmMy5cFrF8CaoDU#
get value 4/vAiLWXkmXj1nyNF3hIxz4R6TI2hoGmMy5cFrF8CaoDU
- -!

**Comment by shadowhand** [comment]
Can you please describe the problem in terms of what you expect and what actually happened?

**Comment by fanhefan** [comment]
Thanks Reply
Use google oauth2 get code api ,it return a non-urlencoded characters # ,
The non-urlencoded characters # disappear when passed to the server.
somebody happen？

code=4/vAiLWXkmXj1nyNF3hIxz4R6TI2hoGmMy5cFrF8CaoDU#

**Comment by shadowhand** [comment]
I have not seen this happen anywhere I use this provider. It may be a server configuration issue.

**Comment by fanhefan** [comment]
@shadowhand maybe google bug??  hah~

**Comment by shadowhand** [comment]
Since no one else has reported this, I am going to assume it is a server configuration issue.
