### ISSUE TITLE
guzzlehttp updated their internal dependencies

### ISSUE THREAD

**Issue by andreyors** [thephpleague/oauth2-google#25]
this fact actually took 6 hours to debug and understand why this library for OAuth stopped working.
-  "guzzlehttp/guzzle": "dev-master#b1a96f6",
-  "guzzlehttp/psr7": "1.3.0",
-  "symfony/event-dispatcher": "dev-master#a158f13",

Fixed directly in composer.json

**Comment by shadowhand** [comment]
Hm... we don't use `dev` version constraints, but I will check this out soon.

**Comment by shadowhand** [comment]
Google provider doesn't depend on Guzzle directly, so this looks like a local version problem.
