### ISSUE TITLE
Wrong method called in Example

### ISSUE THREAD

**Issue by lars-str** [thephpleague/oauth2-google#27]
#28 
In the [Authorization Code Flow](https://github.com/thephpleague/oauth2-google#authorization-code-flow) there is a wrong method called. Instead of `echo $token->getAccessToken();` the line should be `echo $token->getToken();`. `getAccessToken()` does not exists in [AccessToken](https://github.com/thephpleague/oauth2-client/blob/master/src/Token/AccessToken.php#L119-127).

**Comment by shadowhand** [comment]
Fixed by 4575856c1d632e3caa20dbde74f222693b7b8ff7
