### ISSUE TITLE
resource owner url

### ISSUE THREAD

**Issue by bramaningds** [thephpleague/oauth2-google#34]
got error bellow when run getResourceOwner method.
suggestion: change the url to more generic "https://www.googleapis.com/oauth2/v1/userinfo?alt=json".
[error-google-get-resource-owner.txt](https://github.com/thephpleague/oauth2-google/files/454498/error-google-get-resource-owner.txt)

**Comment by no1youknowz** [comment]
I assume that you are using scopes?

	$url = $provider->getAuthorizationUrl([
	    'scope' => [
	    	'https://www.googleapis.com/auth/userinfo.profile'
	    ]
	]);

Ensure that the user.profile scope is available and it will solve your problem.

**Comment by mxdpeep** [comment]
scopes `https://www.googleapis.com/auth/userinfo.email` and `https://www.googleapis.com/auth/userinfo.profile` are deprecated, see [https://developers.google.com/+/web/api/rest/oauth#profile](https://developers.google.com/+/web/api/rest/oauth#profile)

**Comment by shadowhand** [comment]
#65 fixes this by switching to OpenID Connect exclusively.
