### ISSUE TITLE
[question] How can i recieve just user image without '?sz=50' parameter after image extension.

### ISSUE THREAD

**Issue by akhilpundir** [thephpleague/oauth2-google#39]
I am using` getAvatar() `method to get the google user image, the problem is i don't want a small image of sz=50 i would like to get the full image.
if i check the recieved image, a sz=50 parameter gets appended to the image after its extension,
for eg `image.jpg?sz=50`.

please clearify this how can i pass custom parameters or even recieve image without any parameters at all.

**Comment by shadowhand** [comment]
I'm pretty sure you can set the `sz=` to whatever value you want and get an image of that size. Or just remove it and get the largest size available.
