### ISSUE TITLE
approval_prompt conflicts with prompt 

### ISSUE THREAD

**Issue by bgeneto** [thephpleague/oauth2-google#42]
We cannot use something useful like the prompt option, like this: 
`$authUrl = $provider->getAuthorizationUrl(['prompt' => 'select_account consent']);`
Because "AbstractProvider" always adds approval_prompt = 'auto' in "getAuthorizationParameters" method and both options are incompatible and generates na invalid request with "Conflict params: approval_prompt and prompt". Is it safe to comment this line in future versions or there is a better workaround? 
`        $options += [
            'response_type'   => 'code',
            //'approval_prompt' => 'auto'
        ];`

**Comment by shadowhand** [comment]
Please report this issue to the main `oauth2-client` repository, as it cannot be solved here. Thanks!

**Comment by xkobal** [comment]
Simply add option to getAuthorizationUrl() method => `'approval_prompt' => null`

**Comment by shadowhand** [comment]
@xkobal good solution, I will add it.
