### ISSUE TITLE
Problem with multiple accounts on chrome android

### ISSUE THREAD

**Issue by craftpip** [thephpleague/oauth2-google#45]
I've come across some unexpected behaviour with google logins on chrome android. If the device has two google accounts then the login page opens the system's google sync menu.

Expected behaviour: 
1. Sign-in with two google accounts on android phone.
2. Go to the redirected login URL that is provided by google.
3. The google login page is displayed

Current behaviour: 
1. Sign-in with two google accounts on android phone.
2. Go to the redirected login URL that is provided by google.
3. Instead of the google login page, the android sync setting menu opens.
In the android sync menu are listed my accounts, where i can only select the services that can be synced with that account.

I'm absolutely confused with this behaviour, i should be posting a screen snap of the behaviour, but that contains my email address.

Any help is appreciated.

**Comment by ronanchilvers** [comment]
I'm having the same problem. I'm not sure if its an implementation issue in php or a strange behaviour in Chrome.

**Comment by shadowhand** [comment]
Does anyone else have more information on this? Any possibility to reproduce without Android being involved?

**Comment by ronanchilvers** [comment]
@shadowhand i've only experienced it on Android using Chrome. Edge and Firefox both behave correctly. I've never seen it happen on any other platform (desktop and iOS tested). In chrome on Android however it seems to be quite repeatable. Simply implement Google OAuth and attempt sign on with a device hat has more than one Google account registered on it. I believe that should be enough to see it happen. 

Happy to debug or try stuff out on my codebase if that helps.

**Comment by finnito** [comment]
I'm seeing the same issue here too. Occurs on Android, Chrome but works correctly on other browsers. Any information floating around on this?

**Comment by shadowhand** [comment]
A patch for this would be greatly appreciated. I'm not really sure how to go about debugging it.

**Comment by mxdpeep** [comment]
maybe this hotfix I use may help somehow? I use ?relogin=true to force the Google Accounts UI

`

            $authUrl = $provider->getAuthorizationUrl();

            $_SESSION["oauth2state"] = $provider->getState();

            $c = $_COOKIE["login_hint"] ?? false;

            $hint = $c ? "&login_hint=${c}" : "";

            if (isset($_GET["relogin"])) {

                $authUrl = str_replace("approval_prompt=auto", "prompt=select_account", $authUrl);

            } else {

                $authUrl = str_replace("authuser=-1", "authuser=0" . $hint, $authUrl);

            }
            ob_end_flush();

            header("Location: " . $authUrl, true, 303);
`

**Comment by dzero1** [comment]
the issue is still there.

**Comment by mxdpeep** [comment]
> the issue is still there.

I am not experiencing that bug, I use several accounts hosted and one gmail account, I can move between accounts at will

check my [LoginPresenter](https://bitbucket.org/gscloud/lasagna/src/master/app/v1/LoginPresenter.php)
