### ISSUE TITLE
Update to OAuth2 Client v1.0

### ISSUE THREAD

**Issue by shadowhand** [thephpleague/oauth2-google#5]
The provider is currently not in sync with 1.0 (beta) and multiple methods are failing due to signature mismatch.

Refs #4 #3

**Comment by vipconsult** [comment]
:+1:

**Comment by vipconsult** [comment]
will there be any  progress on this ?

**Comment by shadowhand** [comment]
@vipconsult it is hard to find time to work on things when one has a 6 week old baby and a full time job. :wink: I'll be working it this today.

**Comment by ramsey** [comment]
Congrats on the baby!

**Comment by shadowhand** [comment]
Tagged `beta2` moments ago with a number of fixes. Please try it out and let me know if you find additional bugs!
