### ISSUE TITLE
redirect_uri in refresh token request causes error?

### ISSUE THREAD

**Issue by danmartin-epiphany** [thephpleague/oauth2-google#51]
Hello

I've noticed an intermittent problem this week in which Google is rejecting requests to refresh a token if the redirect_uri parameter is included:

`Google->checkResponse(object(Response), array('error' => 'invalid_request', 'error_description' => 'Parameter not allowed for this message type: redirect_uri'))
in vendor/league/oauth2-client/src/Provider/AbstractProvider.php (line 613)`

It doesn't happen every time and can be mitigated by repeatedly making the request until it succeeds.

Alternatively I have been able to make it succeed by extending the Google provider and overriding the getAccessToken() method to remove the parameter when refreshing the token (it is still required for authorization_code grant):

```
    public function getAccessToken($grant, array $options = [])
    {
        $grant = $this->verifyGrant($grant);

        $params = [
            'client_id'     => $this->clientId,
            'client_secret' => $this->clientSecret,
            'redirect_uri'  => $this->redirectUri,
        ];

        if($grant instanceof RefreshToken) {
            unset($params['redirect_uri']);
        }

        $params   = $grant->prepareRequestParameters($params, $options);
        $request  = $this->getAccessTokenRequest($params);
        $response = $this->getParsedResponse($request);
        $prepared = $this->prepareAccessTokenResponse($response);
        $token    = $this->createAccessToken($prepared, $grant);

        return $token;
    }

```

Looking at Google's own library (https://github.com/google/google-auth-library-php/blob/master/src/OAuth2.php#L455) it looks to me as though they don't send the redirect_uri parameter if the grant type is refresh_token.

This problem only started appearing recently and nothing has changed that I can see, so I can only assume that Google has changed their code on some servers and not others.

Is anybody else having any problems and can anyone who understands OAuth better than I do shed any light on the issue? I think I've worked around the issue with the above and I'd be happy to submit a PR to this library, but I don't know for certain if it's the right thing to do or if this is just a temporary issue that will sort itself out in time.

Any help or thoughts appreciated.

Thanks

Dan

**Comment by jpirkey** [comment]
👍

**Comment by jamesgraham** [comment]
We are also seeing refresh tokens not being issued. This is causing full refresh flow to be initiated as a knock-on effect so very urgent.

**Comment by jamesgraham** [comment]
It is possible the token URL needs updating as suggested on `[SO](https://stackoverflow.com/questions/48912655/gmail-api-oauth-error-parameter-not-allowed-for-this-message-type-redirect-uri)`?

**Comment by jpirkey** [comment]
@jamesgraham nice find!  if that works, that's obviously a better long term solution.

**Comment by jamesgraham** [comment]
I plan to fork this repo at the weekend and put the changes there, unless anyone has already tried?

**Comment by jpirkey** [comment]
@jamesgraham afaik just my forks, but don't think they are the correct way to go if just changing the endpoint is the long term solution.

**Comment by jamesgraham** [comment]
It sounds like the URL is the way forward, though I can see no official announcement from Google!

The one challenge will be setting this URL only for refresh purposes. The provider has [only one endpoint defined](https://github.com/thephpleague/oauth2-google/blob/master/src/Provider/Google.php#L52) for the token. The abstract provider also does not differentiate between a refresh token vs access token.

**Comment by shadowhand** [comment]
After #65, which updates the access token URL, this should no longer be an issue. Please report back if it continues to be.
