### ISSUE TITLE
Change accessType in config.yml to get refresh token

### ISSUE THREAD

**Issue by alejgarciarodriguez** [thephpleague/oauth2-google#53]
I am connecting my app to google fitness API. I did the process in google oauth 2.0 playground (https://developers.google.com/oauthplayground) and the response I get is

```
{
  "access_token": "ya29.XXXX....", 
  "token_type": "Bearer", 
  "expires_in": 3600, 
  "refresh_token": "1/...."
}
```

but in the response using oauth2-google refresh token is always null. Can't see the difference here...

I tested using use_state: false and using dev-master version with composer (since google urls seems to have changed, https://github.com/thephpleague/oauth2-google/commit/bca8b14b295aab2e1195994e0050d5a410d63c4b) .

I saw in docs I have to set 'accessType' to 'offline' to get refreshToken, but I don't know where I can change it.

Could anyone help me to fix this? Thanks :)

**Comment by shadowhand** [comment]
`accessType` can be set via the constructor.
