### ISSUE TITLE
How would you sign out or revoke access?

### ISSUE THREAD

**Issue by nostalgicdodo** [thephpleague/oauth2-google#57]
I created a "Log out" link that links to a script that has the following code:

```php
unset( $_SESSION[ 'token' ] );
unset( $_SESSION[ 'oauth2state' ] );

// Re-direct back to the home page
header( 'Location: /' );
```

But when I go to the home page, I'm still logged in.
What am I doing wrong?

**Comment by shadowhand** [comment]
Seems okay to me. Really not enough information to debug the problem.

**Comment by nostalgicdodo** [comment]
I figured it out. I had forgotten to add this line:

```php
session_start();
```

Thanks!

**Comment by shadowhand** [comment]
Happens to the best of us!
