### ISSUE TITLE
Method for locale field

### ISSUE THREAD

**Issue by AndreiIgna** [thephpleague/oauth2-google#60]
Most of the user profile have getter method, but `locale` field is missing in `GoogleUser`. Would be great to have it as a public method

Cheers

**Comment by shadowhand** [comment]
Please make a PR!

**Comment by mxdpeep** [comment]
there is no use for `locale` field in `GoogleUser` as the properties are just:

- id
- name
- first name
- last name
- email
- hosted domain

**Comment by AndreiIgna** [comment]
Hmm that's strange @mxdpeep. Maybe it returns the locale field when different than `en-EN`.

After a few checks, noticed the `locale` field is returned only in `/oauth2/v3/userinfo` endpoint (enabled with option `useOidcMode => true`)
<img width="614" alt="screenshot 2018-12-18 at 13 06 26" src="https://user-images.githubusercontent.com/263021/50153303-5b4c0680-02c6-11e9-8b14-77e3b59543f4.png">

This mode, [named OpenIDConnect in this library](https://github.com/thephpleague/oauth2-google#resource-owner-attributes), should be used by default however, as is the default mode for OAuth apps to access user info. Accessing user info  with Google+ actually has a few cons:
- adds an unnecessary step when setting up, it needs an extra permission to be enabled
- Google+ will shut down eventually https://www.theverge.com/2018/10/8/17951890/google-plus-shut-down-security-api-change-gmail-android

**Comment by mxdpeep** [comment]
I believe G+ is shutting down for sign ups, not as a whole - it will be
part of hosted domains only (business/enterprise social network).
I did NO extra step for OAuth to work on my side, just Google+ API enabled
in Console.

The two endpoints provide attributes with different names and structures.
The GoogleUser class hides these differences for the most common attributes.
<https://github.com/thephpleague/oauth2-google#scopes>

Note that the default scopes include email and profile, which require that
the Google+ API <https://developers.google.com/+/web/api/rest/> is enabled
for your project.
<https://github.com/thephpleague/oauth2-google#testing>

s pozdravem,

*Filip Oščádal*

**Comment by mxdpeep** [comment]
actually I've fiddled with it a bit:

$authUrl = $provider->getAuthorizationUrl([
"approval_prompt" => null,
"prompt" => "select_account consent",
"response_type" => "code",
"scope" => "profile email",
]);


and the result is:

League\OAuth2\Client\Provider\GoogleUser #84a7
response protected => array (5)
emails => array (1)
0 => array (1)
value => "oscadal@gscloud.cz" (18)
id => "115734142237270992095" (21)displayName => "Filip Oščádal"
(16)name => array (2)
familyName => "Oščádal" (10)givenName => "Filip" (5)
image => array (1)
url => "https://lh5.googleusercontent.com/-mNtUiAGV9gY/AAAAAAAAAAI/AAAAAAAADZY/oNEYE_RrJJA/photo.jpg?sz=50"
(98)



s pozdravem,

*Filip Oščádal*

**Comment by mxdpeep** [comment]
and I've added:

$token = $provider->getAccessToken("authorization_code", [
"code" => $_GET["code"],
]);
$ownerDetails = $provider->getResourceOwner($token, [
"useOidcMode" => true,
]);


s pozdravem,

*Filip Oščádal*

**Comment by AndreiIgna** [comment]
The extra step is the one you mentioned @mxdpeep 
> I did NO extra step for OAuth to work on my side, **just Google+ API enabled**
in Console.
If using the `/oauth2/v3/userinfo` endpoint, there's no need to have this API enabled.

Also, more specific info about Google+ shutting down https://developers.googleblog.com/2018/12/google-apis-shutting-down-march-7-2019.html the APIs will be definitely be deprecated.
