### ISSUE TITLE
Google+ APIs will be shut down on March 7, 2019

### ISSUE THREAD

**Issue by inecmc** [thephpleague/oauth2-google#63]
Hi,

According to the [blog](https://developers.google.com/+/api-shutdown), the Google+ API will be shut down on March 7, 2019, and the getResourceOwnerDetailsUrl will be affected.
Is there a plan for using [People API](https://developers.google.com/people/api/rest/) instead of Google+ API in near future?

thanks.

**Comment by karthik-code** [comment]
I am also waiting for the update.

**Comment by Chrisissorry** [comment]
How will this affect the general authentication mechanism? Do I just need to use another scope?

**Comment by mxdpeep** [comment]
The Google+ Sign-in feature is fully deprecated and is being shut down on March 7, 2019. This will be a progressive shutdown, with intermittent failures starting as early as January 28, 2019.

Change the scope from `https://www.googleapis.com/auth/plus.login` to `profile`

**Comment by mxdpeep** [comment]
> Hi,
> 
> According to the [blog](https://developers.google.com/+/api-shutdown), the Google+ API will be shut down on March 7, 2019, and the getResourceOwnerDetailsUrl will be affected.
> Is there a plan for using [People API](https://developers.google.com/people/api/rest/) instead of Google+ API in near future?
> 
> thanks.

People API example:

OAUTH:

$client->authenticate($_GET['code']);
$_SESSION['access_token'] = $client->getAccessToken();
$client->addScope('profile');
$client->addScope('https://www.googleapis.com/auth/contacts.readonly');
$client->setAccessToken($_SESSION['access_token']);
$people_service = new Google_Service_PeopleService($client);

**Comment by Chrisissorry** [comment]
Thanks @mxdpeep, I am currently using the scopes 'email', 'openid', 'profile'. So that should be fine then?

I think on top of that I need to configure the [Google Sign-In](https://developers.google.com/identity/) API. This will create some new credentials in the GCC which need to replace the old ones. 

Did I grasp that correctly?

**Comment by mxdpeep** [comment]
I use GCC to generate OAuth 2.0 client ID credentials = API endpoint +
 Client ID +  Client secret.
If you want to test on localhost, use different ports per application (you
cannot use local domains) and set it in the console too like
*http://localhost:8000/login
<http://localhost:8000/login>*

            $authUrl = $provider->getAuthorizationUrl([
                "approval_prompt" => null,
                "prompt" => "select_account consent",
                "response_type" => "code",
                "scope" => "profile email",
            ]);

            $token = $provider->getAccessToken("authorization_code", [
                "code" => $_GET["code"],
            ]);

            $ownerDetails = $provider->getResourceOwner($token, [
                "useOidcMode" => true,
            ]);

I haven't disabled Google+ APi yet, will test today.


s pozdravem,

*Filip Oščádal*
