### ISSUE TITLE
approval_prompt incorrect fix

### ISSUE THREAD

**Issue by mxdpeep** [thephpleague/oauth2-google#68]
in Google.php, line 64:

        if (empty($options['prompt']) && $this->prompt) {
            $options['prompt'] = $this->prompt;

            // The "approval_prompt" option MUST be removed to prevent conflicts.
            $options['approval_prompt'] = null;
        }

there's an incorrect approval_prompt nullifier that doesn't handle the conflict correctly, this may be a better solution:

        if (empty($options['prompt']) && $this->prompt) {
            $options['prompt'] = $this->prompt;
        }

        // The "approval_prompt" option MUST be removed to prevent conflicts.
        if (!empty($options['prompt'])) {
            $options['approval_prompt'] = null;
        }

**Comment by shadowhand** [comment]
@mxdpeep good catch! Do you want to make a PR?

**Comment by shadowhand** [comment]
Fixed by #69.
