### ISSUE TITLE
Version 0.2.0 requires oauth2-client v ~0.10.0

### ISSUE THREAD

**Issue by onema** [thephpleague/oauth2-google#7]
Hello, 

I assume this is part of the new providers for the upcoming `v1.0.0` of the `oauth2-client`, correct? Should it require version `1.0.*@dev`?

If that is the case, I just got the following error:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for league/oauth2-google ~0.2.0 -> satisfiable by league/oauth2-google[v0.2.0].
    - league/oauth2-google v0.2.0 requires league/oauth2-client ~0.10.0 -> no matching package found.
```
when running composer update with the following requires:

```
{
    "require": {
        "league/oauth2-client":     "1.0.*@dev", // I get the same issue if i use 1.0.0-beta1
        "league/oauth2-google":     "~0.2.0"
    }
}
```
If this repo is not intended for `v1` please disregard this.

**Comment by shadowhand** [comment]
I've just tagged `1.0.0-beta1`, so you should be able to use:

```json
"league/oauth2-google": "~1.0"
```

So long as your `minimum-stability` is `beta` or lower.

**Comment by onema** [comment]
:+1: Thank you!
