### ISSUE TITLE
Issue installing oauth2-google via composer

### ISSUE THREAD

**Issue by zedude22** [thephpleague/oauth2-google#70]
Hello,
I try to install oauth on my vps server running with Ubuntu 14.04. When running php -v I get the following lines:
PHP 5.6.39 (cli) (built: Dec  7 2018 13:48:12)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v6.0.7, Copyright (c) 2002-2016, by ionCube Ltd.
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

But when i run composer require league/oauth2-google, here's what I get:
  Problem 1
    - league/oauth2-google 3.0.0 requires league/oauth2-client ^2.0 -> satisfiable by league/oauth2-client[2.0.0, 2.1.0, 2.2.0, 2.2.1, 2.3.0, 2.3.1, 2.4.0, 2.4.1].
    - league/oauth2-google 3.0.1 requires league/oauth2-client ^2.0 -> satisfiable by league/oauth2-client[2.0.0, 2.1.0, 2.2.0, 2.2.1, 2.3.0, 2.3.1, 2.4.0, 2.4.1].
    - league/oauth2-client 2.4.1 requires php ^5.6|^7.0 -> your PHP version (5.5.9) does not satisfy that requirement.
    - league/oauth2-client 2.4.0 requires php ^5.6|^7.0 -> your PHP version (5.5.9) does not satisfy that requirement.
    - league/oauth2-client 2.3.1 requires php ^5.6|^7.0 -> your PHP version (5.5.9) does not satisfy that requirement.
    - league/oauth2-client 2.3.0 requires php ^5.6|^7.0 -> your PHP version (5.5.9) does not satisfy that requirement.
    - league/oauth2-client 2.2.1 requires php >=5.6.0 -> your PHP version (5.5.9) does not satisfy that requirement.
    - league/oauth2-client 2.2.0 requires php >=5.6.0 -> your PHP version (5.5.9) does not satisfy that requirement.
    - league/oauth2-client 2.1.0 requires php >=5.6.0 -> your PHP version (5.5.9) does not satisfy that requirement.
    - league/oauth2-client 2.0.0 requires php >=5.6.0 -> your PHP version (5.5.9) does not satisfy that requirement.
    - Installation request for league/oauth2-google ^3.0 -> satisfiable by league/oauth2-google[3.0.0, 3.0.1].
Does anybody have a clue for me? I need oauth to send mail via phpmailer...
TIA.
Erwan

**Comment by mxdpeep** [comment]
Ubuntu 14.04 is obsolete
PHP 5.6 is deprecated

upgrade your system and upgrade PHP package, preferably using Ondřej Surý
repository https://deb.sury.org/

apt-get install -y software-properties-common language-pack-en-base
LC_ALL=en_US.UTF-8 add-apt-repository -y ppa:ondrej/php
apt-get update -y
apt-get install -y libapache2-mod-php7.2 openssl php7.2 php7.2-cli
php7.2-curl php7.2-gd php7.2-intl php7.2-json php7.2-mbstring php7.2-mysql
php7.2-readline php7.2-pgsql php7.2-sqlite3 php7.2-xml php7.2-zip

s pozdravem,

*Filip Oščádal*
*https://fredbrooker.gscloud.cz <https://fredbrooker.gscloud.cz>*

**Comment by mxdpeep** [comment]
see http://php.net/supported-versions.php for more information about PHP
support


s pozdravem,

*Filip Oščádal*
*https://fredbrooker.gscloud.cz <https://fredbrooker.gscloud.cz>*

**Comment by shadowhand** [comment]
You can still install version 2.x but I strongly recommend using a supported version of PHP.
