### ISSUE TITLE
Undefined index: family_name

### ISSUE THREAD

**Issue by JellyBellyDev** [thephpleague/oauth2-google#72]
Hi,
thank you very much for your library that I use for some time.
Since I updated the library to `v3.*` I started receiving the notice in subject `Undefined index: family_name`
Can you tell me why?
Thank you

**Comment by shadowhand** [comment]
[`family_name` maps to `getLastName`](https://github.com/thephpleague/oauth2-google/blob/master/src/Provider/GoogleUser.php#L52). The user information is pulled from [OpenID Connect user profile](https://developers.google.com/identity/protocols/OpenIDConnect#obtaininguserprofileinformation).

If you have old tokens, you may need to re-authorize to make sure the correct scopes are required.

**Comment by JellyBellyDev** [comment]
How can I tell who has the old token to re-authorize?
Thanks!

**Comment by shadowhand** [comment]
@JellyBellyDev any token that was created prior to upgrading to v3.x is probably invalid.
