### ISSUE TITLE
How do I install this without composer?

### ISSUE THREAD

**Issue by nom3d** [thephpleague/oauth2-google#78]
I simply want to download the files, upload them to my server and execute the code. I am not familiar with composer and would like to download files just like any other thing. Why can't it be simple?

**Comment by shadowhand** [comment]
That is not possible because there are a variety of dependencies that need to be installed. We do not support installation methods outside of composer.

**Comment by shadowhand** [comment]
If you need a simple way to login users using Google accounts, you might want to look at [Auth0](https://auth0.com).
