### ISSUE TITLE
array of scopes is completly ignored in the constructor

### ISSUE THREAD

**Issue by onema** [thephpleague/oauth2-google#8]
Custom scopes are never set. Using the same code in the example:
```
$provider = new League\OAuth2\Client\Provider\Google([
    'clientId'     => '{google-app-id}',
    'clientSecret' => '{google-app-secret}',
    'redirectUri'  => 'https://example.com/callback-url',
    'scopes'       => ['https://www.googleapis.com/auth/adwords'],
    'hostedDomain' => 'example.com',
]);
```

In this case I'm using the [adwords](https://developers.google.com/adwords/api/docs/guides/authentication) scope, which used to work in the previous version `0.x`, but the scope is never set, and the provider end's up using the default scopes `profile, email`. 

Currently the only way I can see to get around this is to pass this value in the options array when getting the authorization url.

**Comment by shadowhand** [comment]
That's correct. To work around this, you will need to do the following:

```php
$url = $provider->getAuthorizationUrl([
    'scopes' => ['openid', 'email', 'profile', ...],
]);
```

This the only way that scopes can be defined at runtime. Alternatively, you can extend the Google provider with your own class and overload the `getDefaultScopes` method.

**Comment by onema** [comment]
Great, I was looking at some of the other providers and figure that this is the way it is going to be in `v1`. 

Thanks for updating the example!
