### ISSUE TITLE
[Reopen] Undefined index: family_name

### ISSUE THREAD

**Issue by majkel89** [thephpleague/oauth2-google#80]
While using 3.0.1 we face notice `Undefined index: family_name`

It happened for use with google suite account. The `family_name` key was missing in userinfo response.

Already created PR fixing this issue https://github.com/thephpleague/oauth2-google/pull/79

Previous issue https://github.com/thephpleague/oauth2-google/issues/72

**Comment by shadowhand** [comment]
Fixed by #79
