### ISSUE TITLE
AbstractProvider class missing?

### ISSUE THREAD

**Issue by WongCKB** [thephpleague/oauth2-google#84]
hello,

am currently using the Google.php file together with my PHPMailer script, and there seems to be an error in line 11 (screenshot attached).

Anyone able to assist?

![script](https://user-images.githubusercontent.com/35673327/71543096-0e574180-29aa-11ea-8d80-30fb6cfab18f.PNG)
![line 11](https://user-images.githubusercontent.com/35673327/71543097-18794000-29aa-11ea-8562-96219911daee.PNG)

**Comment by shadowhand** [comment]
Install this package with composer, so that it pulls in the necessary dependencies. The `AbstractProvider` class comes from https://github.com/thephpleague/oauth2-client
