### ISSUE TITLE
"invalid state" error when using sample code

### ISSUE THREAD

**Issue by JMCA2** [thephpleague/oauth2-google#85]
When using the sample code I receive the "invalid state" error.

Remove this solves the issue:
` || ($_GET['state'] !== $_SESSION['oauth2state']`

**Comment by shadowhand** [comment]
Removing that code means that security is being reduced; it is critical to keep that to avoid 3rd party hijacking. The fact that it doesn't work with that line probably points to an issue with session configuration.

**Comment by Horttcore** [comment]
I got the same problem ;-(

**Comment by francoisjacquet** [comment]
This is because the $_SESSION is lost if the cookie samesite attribute is set to Strict. Lax works, but security is also reduced!

**Comment by francoisjacquet** [comment]
See the adapted example code to work with RosarioSIS:
https://gitlab.com/francoisjacquet/Google_Social_Login/-/commit/47de8751ea2d185e3f695d2c28bd9ebe16952b66
