### ISSUE TITLE
How to get the user groups?

### ISSUE THREAD

**Issue by Horttcore** [thephpleague/oauth2-google#86]
I've got the right scope, but I can't get the groups out of the request.

```php
'scope' => [
                    'https://www.googleapis.com/auth/userinfo.profile',
                    'https://www.googleapis.com/auth/groups',
                ]
```

There is no function to retrieve any other value out of the GoogleUser object.
Is the group information still in the Guzzle response object?

I hope you get what I mean.

**Comment by shadowhand** [comment]
The token that is returned can be used to access the APIs that are scoped.

**Comment by Horttcore** [comment]
@shadowhand Could you point me in the right direction?

**Comment by shadowhand** [comment]
@Horttcore https://developers.google.com/admin-sdk/directory/v1/reference/groups
