### ISSUE TITLE
Legacy People API

### ISSUE THREAD

**Issue by FMagnanWD** [thephpleague/oauth2-google#88]
Hi,

Some problems with  People API ? (deprecated ??)

403 Forbidden
Legacy People API has not been used in project ... If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry

In Provider/Google.php file at line 79
replace https://www.googleapis.com/plus/v1/people/me? to https://www.googleapis.com/userinfo/v2/me

worked for me

**Comment by shadowhand** [comment]
I'm not sure what you're referring to. The `plus` endpoint hasn't been used since #65.
