### ISSUE TITLE
Include the gender field when fetching the user profile

### ISSUE THREAD

**Issue by najela** [thephpleague/oauth2-google#9]
It is possible to include the `gender` field when fetching user info, but the provider does not currently do it.

Originally reported as thephpleague/oauth2-client#402.

**Comment by shadowhand** [comment]
The fields that are fetched are defined by [this code](https://github.com/thephpleague/oauth2-google/blob/7f7942f357d97a911dc820fdb6de2ece6deaf362/src/Provider/Google.php#L41). You could certainly extend the Google provider class yourself and add additional fields to this, along with changing the GoogleUser class.

I could also make it possible to configure this via the provider options, although doing so would make the GoogleUser class methods potentially inaccurate. Would it be sufficient for your needs if there was a `userFields` option?

**Comment by najela** [comment]
@shadowhand I did configure the code you mentioned earlier and I've enabled the gender field.  Also I think it would be cool if there was a user fields option so I could get other stuff like **locale** etc

**Comment by shadowhand** [comment]
You have the ability to add `userFields` to provider options now. Whatever you provide here will be _merged_ with the default fields.

**Comment by shadowhand** [comment]
I've tagged this in the beta3 release.

**Comment by najela** [comment]
Thanks @shadowhand.. I appreciate :+1:
