### ISSUE TITLE
How do I use thephpleague / oauth2-google to decrypt an idToken JWT string?

### ISSUE THREAD

**Issue by jadelbe418** [thephpleague/oauth2-google#93]
I posted the following issue on Sack Overflow which details this issue:

https://stackoverflow.com/questions/65815949/how-to-use-league-oath-2-integration-to-decrypt-text-based-google-jwt-idtoken-f

What I am wondering is if thephpleague / oauth2-google has a way of decrypting the id_token JWT string independent of the Access token object? Or get the AccessToken object given the id_token JWT? I am working with a front end that does not have access to the value $_GET['code'] vaule used to look up the AccessToken as demonstrated in the integration example [here](https://github.com/thephpleague/oauth2-google#authorization-code-flow).

Thanks!

**Comment by shadowhand** [comment]
This is not something that the library supports.
