### ISSUE TITLE
Use Code Coverage test 

### ISSUE THREAD

**Issue by Yozhef** [thephpleague/oauth2-google#99]
I'm looking at implementing this resource to measure code coverage - https://about.codecov.io/  - 
But we need the rights to the repository to register this project in this service

**Comment by Yozhef** [comment]
@shadowhand what do you think about this?

**Comment by Yozhef** [comment]
https://github.com/thephpleague/oauth2-google/pull/100

**Comment by shadowhand** [comment]
@Yozhef yes I am in favor of it. I have added the required token to this repo's secrets.

**Comment by Yozhef** [comment]
@shadowhand thanks this integration is done =)
